# Generated by Django 3.1.2 on 2021-02-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='secondary_state',
            field=models.JSONField(),
        ),
    ]
